### ISSUE TITLE
How to format scribble in demo json file?

### ISSUE THREAD

**Issue by mrwu-mac** [frank-xwang/InstanceDiffusion#22]
Thank you for your outstanding work. 
I try to format scribble with format [[x1,y1],[x2,y2],...], but got a error as follows,
`scribbles_embeddings[idx] = torch.tensor(scribble) line 72, in prepare_batch;
RuntimeError: expand(torch.FloatTensor{[96, 2]}, size=[40]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)`

**Comment by frank-xwang** [comment]
Hi, could you please provide an example of the scribble you used? Before you do that, it might be helpful to verify the format of the scribbles by referring to this line in our code, which generates scribbles randomly when none is provided:

[https://github.com/frank-xwang/InstanceDiffusion/blob/453b65d3cc2256070831561ab7dcf554d51fc67c/inference.py#L254](https://github.com/frank-xwang/InstanceDiffusion/blob/453b65d3cc2256070831561ab7dcf554d51fc67c/inference.py#L254)

Based on the error message you shared, it appears that the scribble you provided does not conform to the format expected by our code.

**Comment by mrwu-mac** [comment]
The code used to randomly sample the points inside the scribble works for me. But manually giving scribble seems to get a different form of input, resulting in an error.

**Comment by frank-xwang** [comment]
Sorry for the late reply. The scribble should be in the format of [x1, y1, ..., x20, y20]. Hope it helps!

**Comment by Joyce-1103** [comment]
I encounter the same problem, too. And I format the scribble as author said [x1, y1, ..., x20, y20], but some errors appeared as follows, 
Traceback (most recent call last):
  File "inference.py", line 267, in <module>
    scribbles_list = [rescale_scribbles(scribbles, img_info['width'], img_info['height']) for scribbles in scribbles_list]
  File "inference.py", line 267, in <listcomp>
    scribbles_list = [rescale_scribbles(scribbles, img_info['width'], img_info['height']) for scribbles in scribbles_list]
  File "inference.py", line 153, in rescale_scribbles
    return [[scribble[0]/float(width), scribble[1]/float(height)] for scribble in scribbles]
  File "inference.py", line 153, in <listcomp>
    return [[scribble[0]/float(width), scribble[1]/float(height)] for scribble in scribbles]
TypeError: 'int' object is not subscriptable
